import {
    Clock,
    Calendar,
    Users,
    Settings,
    FileText,
    Briefcase,
    Building,
    FolderTree,
    UserPlus,
    LayoutDashboard,
    LogOut,
    LucideProps,
    Check,
    X,
    IdCard,
    CalendarPlus2,
    Search,
    SlidersHorizontal,
    Pencil,
    Plus,
    Loader2,
    Trash,
    Code,
    CalendarX,
    LogIn,
    SquareArrowRight,
    Trash2,
    CheckSquare,
    Vote,
    Eye,
    User,
    Lock,
    ArrowRight,
} from 'lucide-react';

export const Icons = {
    clock: (props: LucideProps) => <Clock className="size-5 stroke-[1.5]" {...props} />,
    calendar: (props: LucideProps) => <Calendar className="size-5 stroke-[1.5]" {...props} />,
    users: (props: LucideProps) => <Users className="size-5 stroke-[1.5]" {...props} />,
    settings: (props: LucideProps) => <Settings className="size-5 stroke-[1.5]" {...props} />,
    fileText: (props: LucideProps) => <FileText className="size-5 stroke-[1.5]" {...props} />,
    briefcase: (props: LucideProps) => <Briefcase className="size-5 stroke-[1.5]" {...props} />,
    building: (props: LucideProps) => <Building className="size-5 stroke-[1.5]" {...props} />,
    folderTree: (props: LucideProps) => <FolderTree className="size-5 stroke-[1.5]" {...props} />,
    userPlus: (props: LucideProps) => <UserPlus className="size-5 stroke-[1.5]" {...props} />,
    dashboard: (props: LucideProps) => <LayoutDashboard className="size-5 stroke-[1.5]" {...props} />,
    logOut: (props: LucideProps) => <LogOut className="size-5 stroke-[1.5]" {...props} />,
    check: (props: LucideProps) => <Check className="size-5 stroke-[1.5]" {...props} />,
    cancel: (props: LucideProps) => <X className="size-5 stroke-[1.5]" {...props} />,
    id: (props: LucideProps) => <IdCard className="size-5 stroke-[1.5]" {...props} />,
    calendarPlus: (props: LucideProps) => <CalendarPlus2 className="size-5 stroke-[1.5]" {...props} />,
    search: (props: LucideProps) => <Search className="size-5 stroke-[1.5]" {...props} />,
    action: (props: LucideProps) => <SlidersHorizontal className="size-5 stroke-[1.5]" {...props} />,
    edit: (props: LucideProps) => <Pencil className="size-5 stroke-[1.5]" {...props} />,
    plus: (props: LucideProps) => <Plus className="size-5 stroke-[1.5]" {...props} />,
    spinner: (props: LucideProps) => <Loader2 className="size-5 stroke-[1.5]" {...props} />,
    trash: (props: LucideProps) => <Trash className="size-5 stroke-[1.5]" {...props} />,
    code: (props: LucideProps) => <Code className="size-5 stroke-[1.5]" {...props} />,
    calendarX: (props: LucideProps) => <CalendarX className="size-5 stroke-[1.5]" {...props} />,
    login: (props: LucideProps) => <LogIn className="size-5 stroke-[1.5]" {...props} />,
    squareArrowRight: (props: LucideProps) => <SquareArrowRight className="size-5 stroke-[1.5]" {...props} />,
    delete: (props: LucideProps) => <Trash2 className="size-5 stroke-[1.5]" {...props} />,
    checkSquare: (props: LucideProps) => <CheckSquare className="size-5 stroke-[1.5]" {...props} />,
    vote: (props: LucideProps) => <Vote className="size-5 stroke-[1.5]" {...props} />,
    eye: (props: LucideProps) => <Eye className="size-5 stroke-[1.5]" {...props} />,
    user: (props: LucideProps) => <User className="size-5 stroke-[1.5]" {...props} />,
    lock: (props: LucideProps) => <Lock className="size-5 stroke-[1.5]" {...props} />,
    arrowRight: (props: LucideProps) => <ArrowRight className="size-5 stroke-[1.5]" {...props} />,
};
